name = "wecom-komari-cf"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
SENDKEY = "set_a_sendkey"
KOMARI_URL = "https://km.o0oo.cc"
KOMARI_API_KEY = "komari-BRZsSvtpYBduOYqMFZEIWlTnpqtBDqmz"
KOMARI_USERNAME = "xiucai"
KOMARI_PASSWORD = "A204800b_"
TELEGRAM_BOT_TOKEN = "8798918630:AAG3eDS2RJ3GlEBn1SwylE0MiRHSiuOyb0Q"
TELEGRAM_WEBHOOK_SECRET = "204800"
TELEGRAM_ALLOWED_USERS = "691245891"
